"""
ChaosMesh Arena — Core Gymnasium Environment.

Implements gymnasium.Env with RFC 001/002/003 compliant API:
  reset() → ObservationModel
  step(action) → (obs, reward, done, truncated, info)
  state() → FullStateModel

This is the main entrypoint for RL training loops.
"""

from __future__ import annotations

import time
import uuid
from typing import Any, Optional, SupportsFloat

import gymnasium as gym
import structlog

from chaosmesh_arena.bus.message_bus import MessageBus
from chaosmesh_arena.config import get_settings
from chaosmesh_arena.memory.belief_tracker import BeliefTracker
from chaosmesh_arena.models import (
    ActionModel,
    ActionType,
    AgentBeliefModel,
    AgentRole,
    FullStateModel,
    IncidentLevel,
    IncidentStatus,
    ObservationModel,
    RewardBreakdown,
    StepResult,
)
from chaosmesh_arena.progression.difficulty_fsm import DifficultyFSM, EpisodeResult
from chaosmesh_arena.rewards.calculator import RewardCalculator
from chaosmesh_arena.sim.cluster_state import ClusterStateMachine
from chaosmesh_arena.sim.failure_injector import FailureInjector
from chaosmesh_arena.sim.log_synthesizer import LogSynthesizer
from chaosmesh_arena.sim.metrics_engine import MetricsEngine
from chaosmesh_arena.templates.incident_registry import IncidentRegistry

log = structlog.get_logger(__name__)


class ChaosMeshArenaEnv(gym.Env):
    """
    ChaosMesh Arena — Multi-agent adversarial SRE training environment.

    A Gymnasium-compatible environment where a swarm of 5 specialized agents
    collaboratively diagnose and remediate Kubernetes infrastructure incidents
    generated by an adversarial LLM Chaos Engine.

    Spec: OpenEnv RFC 001/002/003
    Version: 0.1.0

    Example usage:
        import gymnasium as gym
        import chaosmesh_arena  # registers the env

        env = gym.make("ChaosMeshArena-v0")
        obs, info = env.reset(options={"level": 1})
        action = env.action_space.sample()
        obs, reward, done, truncated, info = env.step(action)
    """

    metadata = {"render_modes": ["json", "human"], "render_fps": 1}

    def __init__(
        self,
        level: IncidentLevel = IncidentLevel.LEVEL_1,
        seed: Optional[int] = None,
        demo_mode: bool | None = None,
    ):
        super().__init__()
        self._settings = get_settings()
        self._level = level
        self._seed = seed
        self._demo_mode = demo_mode if demo_mode is not None else self._settings.demo_mode

        # ── Simulation sub-systems ────────────────────────────────────────────
        self._cluster = ClusterStateMachine(seed=seed)
        self._metrics = MetricsEngine(seed=seed)
        self._logs = LogSynthesizer(seed=seed)
        self._injector = FailureInjector(self._cluster, self._metrics, self._logs)

        # ── Phase 2 systems ───────────────────────────────────────────────────
        self._belief_tracker = BeliefTracker()
        self._difficulty_fsm = DifficultyFSM(initial_level=level)
        self._reward_calc = RewardCalculator(
            level=level,
            belief_tracker=self._belief_tracker,
            max_messages=self._settings.max_episode_messages,
        )
        self._registry = IncidentRegistry(self._injector)
        self._bus = MessageBus(
            redis_url=getattr(self._settings, 'redis_url', 'redis://localhost:6379')
        )
        if seed is not None:
            self._registry.seed(seed)

        # ── Episode state ─────────────────────────────────────────────────────
        self._episode_id: str = ""
        self._step: int = 0
        self._wall_start: float = 0.0
        self._message_count: int = 0
        self._cumulative_reward: float = 0.0
        self._terminated: bool = False
        self._truncated: bool = False
        self._action_history: list[ActionModel] = []
        self._reward_history: list[RewardBreakdown] = []
        self._beliefs: dict[str, AgentBeliefModel] = {}
        self._all_messages: list = []
        self._recent_action_types: list[str] = []

        # ── Gymnasium action / observation spaces ─────────────────────────────
        # Note: For LLM-based agents, spaces are Dict/Text-like.
        # We use gymnasium.spaces.Text for compatibility but the real interface
        # is the Pydantic ActionModel / ObservationModel.
        import numpy as np
        from gymnasium import spaces

        self.action_space = spaces.Dict({
            "action_type": spaces.Discrete(len(ActionType)),
            "agent": spaces.Discrete(len(AgentRole)),
            "target": spaces.Text(max_length=128),
        })
        self.observation_space = spaces.Dict({
            "episode_id": spaces.Text(max_length=64),
            "step": spaces.Box(low=0, high=10000, shape=(1,), dtype=np.int32),
            "sim_time_minutes": spaces.Box(low=0, high=60, shape=(1,), dtype=np.float32),
            "incident_count": spaces.Box(low=0, high=10, shape=(1,), dtype=np.int32),
            "unhealthy_pods": spaces.Box(low=0, high=50, shape=(1,), dtype=np.int32),
        })

        log.info("env_initialized", level=level, demo_mode=self._demo_mode)

    # ═══════════════════════════════════════════════════════════════════════════
    # Gymnasium Core API (RFC 001/002/003)
    # ═══════════════════════════════════════════════════════════════════════════

    def reset(
        self,
        *,
        seed: Optional[int] = None,
        options: Optional[dict] = None,
    ) -> tuple[ObservationModel, dict[str, Any]]:
        """
        RFC 001 — Reset environment to initial state.

        Returns:
            (observation, info)  where observation is typed ObservationModel
        """
        super().reset(seed=seed)
        if seed is not None:
            self._seed = seed
            self._registry.seed(seed)

        # Override level from options — also sync DifficultyFSM
        if options and "level" in options:
            self._level = IncidentLevel(options["level"])
            self._difficulty_fsm.force_level(self._level)
            self._reward_calc.set_level(self._level)

        # Reset all sub-systems
        self._cluster.reset(seed=self._seed)
        self._metrics.reset()
        self._logs.reset()

        # Episode bookkeeping
        self._episode_id = str(uuid.uuid4())
        self._step = 0
        self._wall_start = time.time()
        self._message_count = 0
        self._cumulative_reward = 0.0
        self._terminated = False
        self._truncated = False
        self._action_history.clear()
        self._reward_history.clear()
        self._beliefs.clear()
        self._all_messages.clear()
        self._recent_action_types.clear()
        self._reward_calc.reset_message_count()
        self._belief_tracker.clear_episode(self._episode_id)

        # Inject an initial incident using the registry (seeded selection)
        self._inject_incident_for_level(self._level)

        obs = self._build_observation()
        info = {
            "episode_id": self._episode_id,
            "level": self._level.value,
            "difficulty_state": self._difficulty_fsm.state_dict(),
        }

        log.info("episode_reset", episode_id=self._episode_id, level=self._level)
        return obs, info

    def step(
        self,
        action: ActionModel | dict,
    ) -> tuple[ObservationModel, SupportsFloat, bool, bool, dict[str, Any]]:
        """
        RFC 002 — Process one agent action.

        Args:
            action: ActionModel (preferred) or raw dict

        Returns:
            (observation, reward, terminated, truncated, info)
        """
        # Accept dict for compatibility with gym.utils.env_checker
        if isinstance(action, dict):
            action = ActionModel(**action)

        if not action.is_safe():
            log.warning("unsafe_action_blocked", action=action.action_type, target=action.target)
            reward = RewardBreakdown(individual=-2.0, total=-2.0)
            obs = self._build_observation()
            return obs, reward, False, False, {"blocked": True, "reason": "unsafe_action"}

        self._step += 1
        self._action_history.append(action)
        self._recent_action_types.append(action.action_type.value)

        # ── Apply action to cluster state ─────────────────────────────────────
        self._apply_action(action)

        # ── Advance simulation time ────────────────────────────────────────────
        self._cluster.tick(real_seconds=1.0)

        # ── Generate fresh metrics and logs ───────────────────────────────────
        for pod in self._cluster._pods.values():
            self._metrics.snapshot_pod(pod)
        for svc in self._cluster._services.values():
            self._metrics.snapshot_service(svc)
        self._logs.generate_normal(
            [p for p in self._cluster._pods.values()][:3], n=3
        )

        # ── Update belief tracker if action carries a hypothesis ───────────────
        if hasattr(action, 'message') and action.message and action.message.content.hypothesis:
            belief = AgentBeliefModel(
                agent=action.agent,
                hypothesis=action.message.content.hypothesis,
                confidence=action.message.content.confidence,
                supporting_evidence=action.message.content.evidence or [],
            )
            self._beliefs[action.agent.value] = belief
            self._belief_tracker.update_belief(self._episode_id, self._step, belief)

        # ── Compute reward (RewardCalculator) ─────────────────────────────────
        reward = self._compute_reward(action)
        self._reward_history.append(reward)
        self._cumulative_reward += reward.total

        # ── Track messages ─────────────────────────────────────────────────────
        if action.message:
            self._all_messages.append(action.message)
            self._message_count += 1
            self._reward_calc.increment_message_count()

        # ── Check termination ─────────────────────────────────────────────────
        self._terminated = self._injector.is_all_resolved()
        self._truncated = self._check_truncation()

        # ── Difficulty FSM: record resolved episodes ───────────────────────────
        if self._terminated:
            ep_result = EpisodeResult(
                episode_id=self._episode_id,
                level=self._level,
                resolved=True,
                cumulative_reward=self._cumulative_reward,
                sim_time_minutes=self._cluster.sim_time_minutes,
                target_mttr_minutes={1:3.0,2:6.0,3:9.0,4:12.0,5:18.0}.get(
                    self._level.value, 5.0
                ),
                step_count=self._step,
            )
            advanced = self._difficulty_fsm.record_result(ep_result)
            if advanced:
                self._level = self._difficulty_fsm.current_level
                self._reward_calc.set_level(self._level)
                log.info("difficulty_level_advanced", new_level=self._level.value)

        obs = self._build_observation()
        info = {
            "episode_id": self._episode_id,
            "step": self._step,
            "reward_breakdown": reward.model_dump(),
            "cumulative_reward": self._cumulative_reward,
            "sim_time_minutes": self._cluster.sim_time_minutes,
            "difficulty_state": self._difficulty_fsm.state_dict(),
        }

        log.debug(
            "step_complete",
            step=self._step,
            agent=action.agent,
            action=action.action_type,
            reward=reward.total,
            terminated=self._terminated,
        )
        return obs, reward, self._terminated, self._truncated, info

    def state(self) -> FullStateModel:
        """RFC 003 — Return complete internal state (including ground truth)."""
        return FullStateModel(
            episode_id=self._episode_id,
            step=self._step,
            sim_time_minutes=self._cluster.sim_time_minutes,
            wall_time_seconds=time.time() - self._wall_start if self._wall_start else 0.0,
            cluster_state=self._cluster.snapshot(),
            active_incidents=self._injector.get_active_incidents(),
            all_messages=list(self._all_messages),
            all_beliefs=dict(self._beliefs),
            action_history=list(self._action_history),
            reward_history=list(self._reward_history),
            current_level=self._level,
            episode_status=(
                IncidentStatus.RESOLVED if self._terminated
                else IncidentStatus.TIMED_OUT if self._truncated
                else IncidentStatus.ACTIVE
            ),
            cumulative_reward=self._cumulative_reward,
        )

    def render(self) -> dict[str, Any] | str:
        """Return cluster state JSON for dashboard visualization."""
        state = self.state()
        return state.model_dump()

    def close(self) -> None:
        log.info("env_closed", episode_id=self._episode_id)
        self._belief_tracker.reset()

    @property
    def difficulty_fsm(self) -> DifficultyFSM:
        """Expose FSM for external curriculum control."""
        return self._difficulty_fsm

    @property
    def message_bus(self) -> MessageBus:
        """Expose the message bus for agent wiring."""
        return self._bus

    @property
    def belief_tracker(self) -> BeliefTracker:
        """Expose belief tracker for agent wiring."""
        return self._belief_tracker

    # ═══════════════════════════════════════════════════════════════════════════
    # Internal Helpers
    # ═══════════════════════════════════════════════════════════════════════════

    def _inject_incident_for_level(self, level: IncidentLevel) -> None:
        """Inject an incident using the IncidentRegistry (seeded selection)."""
        try:
            result = self._registry.inject(level)
            log.info(
                "incident_injected_via_registry",
                incident_id=result.incident.incident_id,
                level=level.value,
            )

            # RFC compatibility: level 1 resets must show at least one unhealthy pod.
            # Some registry templates (for example node/image focused failures) can keep
            # pods technically ready at injection time, so add a deterministic fallback.
            if level == IncidentLevel.LEVEL_1:
                pods = self._cluster.snapshot().pods
                unhealthy = sum(1 for pod in pods.values() if not pod.ready)
                if unhealthy == 0:
                    self._injector.inject_pod_crash()
                    log.info("incident_injected_level1_pod_fallback")
        except Exception as e:
            log.error("incident_injection_failed", error=str(e), level=level)
            # Hard fallback — direct injector call
            try:
                fallback_map = {
                    IncidentLevel.LEVEL_1: self._injector.inject_pod_crash,
                    IncidentLevel.LEVEL_2: self._injector.inject_cascading_db_timeout,
                    IncidentLevel.LEVEL_3: self._injector.inject_ambiguous_attack_vs_misconfig,
                    IncidentLevel.LEVEL_4: self._injector.inject_level4_dynamic_failure,
                    IncidentLevel.LEVEL_5: self._injector.inject_level5_compound_chaos,
                }
                fallback_map.get(level, self._injector.inject_pod_crash)()
            except Exception as e2:
                log.error("fallback_injection_failed", error=str(e2))

    def _apply_action(self, action: ActionModel) -> None:
        """Apply agent action to the cluster state machine."""
        if action.action_type == ActionType.RESTART_POD:
            self._cluster.restore_pod(action.target)
        elif action.action_type == ActionType.SCALE_DEPLOYMENT:
            # Scaling: restore service health
            self._cluster.restore_service(action.target)
        elif action.action_type == ActionType.ROLLBACK_DEPLOYMENT:
            self._cluster.restore_pod(action.target)
        elif action.action_type == ActionType.DECLARE_RESOLVED:
            # Agent declares the incident resolved — attempt remediation
            incidents = self._injector.get_active_incidents()
            for incident in incidents:
                self._injector.remediate(incident.incident_id, action_pod=action.target or None)
        elif action.action_type == ActionType.SEND_MESSAGE:
            if action.message:
                self._all_messages.append(action.message)
        # Observation actions (GET_LOGS, QUERY_METRICS, etc.) don't mutate state

    def _compute_reward(self, action: ActionModel) -> RewardBreakdown:
        """
        Delegates to RewardCalculator (Phase 2).
        Level-adjusted weights, belief accuracy, chaos adaptation included.
        """
        return self._reward_calc.compute(
            action=action,
            obs=self._build_observation(),
            cluster=self._cluster,
            injector=self._injector,
            episode_id=self._episode_id,
        )

    def _build_observation(self) -> ObservationModel:
        """Build a typed ObservationModel from current simulation state."""
        cluster_snapshot = self._cluster.snapshot()
        active_incidents = self._injector.get_active_incidents()
        recent_metrics = self._metrics.get_recent_snapshots(last_n=20)
        recent_logs = self._logs.get_recent(n=20)
        recent_messages = list(self._all_messages[-10:]) if self._all_messages else []

        # Include latest beliefs from BeliefTracker
        current_beliefs = self._belief_tracker.get_current_beliefs(self._episode_id)
        merged_beliefs = {**current_beliefs, **self._beliefs}

        return ObservationModel(
            episode_id=self._episode_id,
            step=self._step,
            sim_time_minutes=self._cluster.sim_time_minutes,
            cluster_state=cluster_snapshot,
            active_incidents=active_incidents,
            recent_metrics=recent_metrics,
            recent_logs=recent_logs,
            agent_messages=recent_messages,
            agent_beliefs=merged_beliefs,
            available_tools=list(ActionType),
            current_level=self._level,
        )

    def _check_truncation(self) -> bool:
        """Check if the episode should be truncated (timeout conditions)."""
        settings = self._settings
        if self._demo_mode and self._step >= settings.demo_fast_max_steps:
            log.warning("episode_demo_step_cap", step=self._step, cap=settings.demo_fast_max_steps)
            return True

        # Wall-clock limit (for demo mode)
        if self._demo_mode:
            wall_elapsed = time.time() - self._wall_start
            wall_limit = min(settings.max_episode_wall_seconds, settings.demo_fast_wall_seconds)
            if wall_elapsed > wall_limit:
                log.warning("episode_wall_timeout", elapsed=wall_elapsed)
                return True
        # Simulated time limit
        if self._cluster.sim_time_minutes > settings.max_sim_minutes:
            log.warning("episode_sim_timeout", sim_time=self._cluster.sim_time_minutes)
            return True
        # Message count limit
        if self._message_count >= settings.max_episode_messages:
            log.warning("episode_message_limit", count=self._message_count)
            return True
        return False
