"""
ChaosMesh Arena — HTML Episode Report Generator.

Generates a self-contained HTML post-mortem report for a completed episode.
No external dependencies in the output — single file, shareable.
"""

from __future__ import annotations

from typing import TYPE_CHECKING

if TYPE_CHECKING:
    from chaosmesh_arena.database.models_db import EpisodeResult

_TEMPLATE = """<!DOCTYPE html>
<html lang="en">
<head>
<meta charset="UTF-8">
<meta name="viewport" content="width=device-width, initial-scale=1.0">
<title>ChaosMesh Arena — Episode Report {{ episode_id_short }}</title>
<style>
  :root {
    --bg: #0f1117; --card: #1a1d27; --border: #2a2d3e;
    --accent: #7c3aed; --success: #10b981; --warn: #f59e0b; --danger: #ef4444;
    --text: #e2e8f0; --muted: #94a3b8;
    --font: 'Inter', system-ui, sans-serif;
  }
  * { box-sizing: border-box; margin: 0; padding: 0; }
  body { background: var(--bg); color: var(--text); font-family: var(--font); padding: 2rem; }
  h1 { font-size: 1.8rem; font-weight: 700; margin-bottom: 0.25rem; }
  h2 { font-size: 1.1rem; font-weight: 600; color: var(--muted); margin-bottom: 1.5rem; }
  h3 { font-size: 1rem; font-weight: 600; margin-bottom: 1rem; color: var(--text); }
  .grid { display: grid; grid-template-columns: repeat(auto-fit, minmax(180px, 1fr)); gap: 1rem; margin: 2rem 0; }
  .card { background: var(--card); border: 1px solid var(--border); border-radius: 12px; padding: 1.25rem; }
  .card .label { font-size: 0.75rem; color: var(--muted); text-transform: uppercase; letter-spacing: 0.05em; }
  .card .value { font-size: 2rem; font-weight: 700; margin-top: 0.25rem; }
  .card .value.ok { color: var(--success); }
  .card .value.warn { color: var(--warn); }
  .card .value.err { color: var(--danger); }
  .score-bar { height: 8px; border-radius: 4px; background: var(--border); margin-top: 0.5rem; overflow: hidden; }
  .score-bar .fill { height: 100%; background: linear-gradient(90deg, var(--accent), var(--success)); border-radius: 4px; transition: width 1s ease; }
  table { width: 100%; border-collapse: collapse; font-size: 0.85rem; }
  th { text-align: left; padding: 0.6rem 1rem; color: var(--muted); font-weight: 500; border-bottom: 1px solid var(--border); font-size: 0.75rem; text-transform: uppercase; }
  td { padding: 0.6rem 1rem; border-bottom: 1px solid var(--border); }
  tr:last-child td { border-bottom: none; }
  .badge { display: inline-block; padding: 0.2rem 0.5rem; border-radius: 4px; font-size: 0.7rem; font-weight: 600; text-transform: uppercase; }
  .badge-green { background: rgba(16,185,129,0.15); color: var(--success); }
  .badge-red { background: rgba(239,68,68,0.15); color: var(--danger); }
  .badge-yellow { background: rgba(245,158,11,0.15); color: var(--warn); }
  .badge-purple { background: rgba(124,58,237,0.15); color: #a78bfa; }
  .section { margin: 2rem 0; }
  .logo { color: var(--accent); font-weight: 800; font-size: 1rem; letter-spacing: -0.02em; margin-bottom: 1.5rem; }
  footer { margin-top: 3rem; text-align: center; color: var(--muted); font-size: 0.75rem; }
</style>
</head>
<body>
<div class="logo">⚡ ChaosMesh Arena</div>
<h1>Episode Post-Mortem</h1>
<h2>{{ episode_id }} &nbsp;·&nbsp; Level {{ level }} &nbsp;·&nbsp; {{ created_at }}</h2>

<div class="grid">
  <div class="card">
    <div class="label">Score</div>
    <div class="value {{ score_class }}">{{ score_pct }}%</div>
    <div class="score-bar"><div class="fill" style="width:{{ score_pct }}%"></div></div>
  </div>
  <div class="card">
    <div class="label">Outcome</div>
    <div class="value {{ outcome_class }}">{{ outcome }}</div>
  </div>
  <div class="card">
    <div class="label">Steps Taken</div>
    <div class="value">{{ steps }}</div>
  </div>
  <div class="card">
    <div class="label">Sim MTTR</div>
    <div class="value">{{ mttr }}m</div>
  </div>
  <div class="card">
    <div class="label">Total Reward</div>
    <div class="value">{{ cumulative_reward }}</div>
  </div>
</div>

<div class="section card">
  <h3>Action Timeline</h3>
  <table>
    <thead>
      <tr>
        <th>#</th><th>Agent</th><th>Action</th><th>Target</th><th>Reward</th>
      </tr>
    </thead>
    <tbody>
      {{ action_rows }}
    </tbody>
  </table>
</div>

<footer>Generated by ChaosMesh Arena &nbsp;·&nbsp; chaosmesh.io</footer>
</body>
</html>
"""


def _badge(value: str, agent_role: str) -> str:
    colors = {
        "incident_commander": "badge-purple",
        "diagnostician": "badge-yellow",
        "remediator": "badge-red",
        "communicator": "badge-green",
        "security_analyst": "badge-yellow",
    }
    cls = colors.get(agent_role.lower(), "badge-purple")
    return f'<span class="badge {cls}">{value}</span>'


def _reward_cell(reward: float) -> str:
    if reward > 0:
        return f'<span style="color:#10b981">+{reward:.3f}</span>'
    elif reward < 0:
        return f'<span style="color:#ef4444">{reward:.3f}</span>'
    return f'<span style="color:#94a3b8">0.000</span>'


async def generate_episode_report(record: "EpisodeResult") -> str:
    """Generate a self-contained HTML post-mortem for an episode."""
    score_pct = round(record.score * 100, 1)
    score_class = "ok" if score_pct >= 70 else ("warn" if score_pct >= 40 else "err")
    outcome = "✅ Resolved" if record.resolved else "⏱ Timed Out"
    outcome_class = "ok" if record.resolved else "warn"

    # Build action rows
    action_log = record.action_log or []
    rows = []
    for i, step in enumerate(action_log, start=1):
        agent = step.get("agent", "—")
        action_type = step.get("action_type", "—")
        target = step.get("target", "—") or "—"
        reward = step.get("reward", 0.0)
        rows.append(
            f"<tr>"
            f"<td>{i}</td>"
            f"<td>{_badge(agent, agent)}</td>"
            f"<td>{action_type.replace('_', ' ').title()}</td>"
            f"<td><code style='font-size:0.8rem'>{target}</code></td>"
            f"<td>{_reward_cell(reward)}</td>"
            f"</tr>"
        )

    action_rows = "\n".join(rows) if rows else "<tr><td colspan='5' style='color:var(--muted);text-align:center'>No actions logged</td></tr>"

    html = _TEMPLATE
    replacements = {
        "{{ episode_id_short }}": record.episode_id[:8],
        "{{ episode_id }}": record.episode_id,
        "{{ level }}": str(record.level),
        "{{ created_at }}": record.created_at.strftime("%Y-%m-%d %H:%M UTC") if record.created_at else "",
        "{{ score_pct }}": str(score_pct),
        "{{ score_class }}": score_class,
        "{{ outcome }}": outcome,
        "{{ outcome_class }}": outcome_class,
        "{{ steps }}": str(record.steps),
        "{{ mttr }}": str(round(record.mttr_minutes, 1)),
        "{{ cumulative_reward }}": str(round(record.cumulative_reward, 3)),
        "{{ action_rows }}": action_rows,
    }
    for placeholder, value in replacements.items():
        html = html.replace(placeholder, value)
    return html
